INCLUDEPATH *= $$PWD/src/lib
INCLUDEPATH *= $$PWD/autogenerated/src/lib

OUT_FOLDER = $$absolute_path($$relative_path($$PWD, $$_PRO_FILE_PWD_), $$OUT_PWD)
win32:CONFIG(release, debug|release) {
    LIBS += -L$$OUT_FOLDER/release -lvsyntaxhighlighting
} else:win32:CONFIG(debug, debug|release) {
    LIBS += -L$$OUT_FOLDER/debug -lvsyntaxhighlighting
} else:unix {
    LIBS += -L$$OUT_FOLDER -lVSyntaxHighlighting
}
